### ISSUE TITLE
[Bug] Subprocess to install build dependencies did not run successfully.

### ISSUE THREAD

**Issue by popcsev** [GamestonkTerminal/GamestonkTerminal#1451]
After creating the environment `conda env create -n gst --file build/conda/conda-3-8-env.yaml` I tried to install with poetry but it failed.

Next, I tried to install with `pip install -r requirements.txt` however I run into the error pasted below. 

- OS: 12.0.1
- Python 3.8.12

```
Collecting osqp==0.6.2.post5
  Using cached osqp-0.6.2.post5.tar.gz (226 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [162 lines of output]
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.1.30-py3-none-any.whl (3.9 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-6.4.2-py3-none-any.whl (37 kB)
      Collecting qdldl
        Using cached qdldl-0.1.5.post0.tar.gz (69 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting numpy==1.21.0
        Using cached numpy-1.21.0-cp38-cp38-macosx_11_0_arm64.whl (12.1 MB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting packaging>=20.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting scipy>=0.13.2
        Using cached scipy-1.8.0-cp38-cp38-macosx_12_0_arm64.whl (28.5 MB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
      Building wheels for collected packages: qdldl
        Building wheel for qdldl (setup.py): started
        Building wheel for qdldl (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [52 lines of output]
            running bdist_wheel
            running build
            running build_ext
            Traceback (most recent call last):
              File "/private/var/folders/5f/075258sn2wz0s6vh9xm0hm5m0000gn/T/pip-install-qx5g0dyi/qdldl_3766d9ca4c584176bdc17494739a6cfb/setup.py", line 78, in build_extensions
                check_output(['cmake', '--version'])
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/subprocess.py", line 415, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/subprocess.py", line 493, in run
                with Popen(*popenargs, **kwargs) as process:
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/subprocess.py", line 858, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/subprocess.py", line 1704, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/5f/075258sn2wz0s6vh9xm0hm5m0000gn/T/pip-install-qx5g0dyi/qdldl_3766d9ca4c584176bdc17494739a6cfb/setup.py", line 110, in <module>
                setup(name='qdldl',
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
                return distutils.core.setup(**attrs)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
                return run_commands(dist)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
                dist.run_commands()
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
                _build_ext.run(self)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
                self.build_extensions()
              File "/private/var/folders/5f/075258sn2wz0s6vh9xm0hm5m0000gn/T/pip-install-qx5g0dyi/qdldl_3766d9ca4c584176bdc17494739a6cfb/setup.py", line 80, in build_extensions
                raise RuntimeError("CMake must be installed to build qdldl")
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
        Running setup.py clean for qdldl
      Failed to build qdldl
      Installing collected packages: wheel, tomli, setuptools, pyparsing, numpy, scipy, packaging, oldest-supported-numpy, setuptools_scm, qdldl
        Running setup.py install for qdldl: started
        Running setup.py install for qdldl: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for qdldl did not run successfully.
        │ exit code: 1
        ╰─> [56 lines of output]
            running install
            /Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running build_ext
            Traceback (most recent call last):
              File "/private/var/folders/5f/075258sn2wz0s6vh9xm0hm5m0000gn/T/pip-install-qx5g0dyi/qdldl_3766d9ca4c584176bdc17494739a6cfb/setup.py", line 78, in build_extensions
                check_output(['cmake', '--version'])
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/subprocess.py", line 415, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/subprocess.py", line 493, in run
                with Popen(*popenargs, **kwargs) as process:
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/subprocess.py", line 858, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/subprocess.py", line 1704, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/5f/075258sn2wz0s6vh9xm0hm5m0000gn/T/pip-install-qx5g0dyi/qdldl_3766d9ca4c584176bdc17494739a6cfb/setup.py", line 110, in <module>
                setup(name='qdldl',
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
                return distutils.core.setup(**attrs)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
                return run_commands(dist)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
                dist.run_commands()
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
                return orig.install.run(self)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 670, in run
                self.run_command('build')
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
                _build_ext.run(self)
              File "/Users/markpopcsev/miniconda3/envs/gst/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
                self.build_extensions()
              File "/private/var/folders/5f/075258sn2wz0s6vh9xm0hm5m0000gn/T/pip-install-qx5g0dyi/qdldl_3766d9ca4c584176bdc17494739a6cfb/setup.py", line 80, in build_extensions
                raise RuntimeError("CMake must be installed to build qdldl")
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> qdldl
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Additional context**
Add any other information that you think could be useful for us.

**Comment by piiq** [comment]
Hey @popcsev Based on the error message I can see that pip is trying to build qdld which is a third level dependency for the pyportfolioopt package. This happens when pip can't find pre-built wheels for your platform. This whole dep branch has not yet been updated for the m1 architecture so only rosetta binaries count. I'm using an m1 mac with Monterrey my self and I've spent some time investigating the support for m1 just this January.
I can assume that you have an m1 version of miniconda installed. If this is the case - please download and install the rosetta version which has all the pre-built binaries.
My installations routine is:

```bash
conda env create -n gst --file build/conda/conda-3-8-env.yaml
conda activate gst
pip install poetry
poetry install
```

Please let me know if you have the rosetta version of conda and if with this version the commands mentioned in this comment work.

**Comment by piiq** [comment]
Closing the issue due to inactivity. If anyone pops up here, please refer to my previous comment for the environment installation instructions

**Comment by sanurielf** [comment]
Hi,

Same problem here. Since [qdldl](https://pypi.org/project/qdldl) does not have OSX arm64 builds, poetry/pip will build it from the source. This can be solved just by installing CMake (qdldl dependency) before running `poetry install`:

```
conda env create -n gst --file build/conda/conda-3-8-env.yaml
conda install cmake
poetry install
```
