### ISSUE TITLE
[Bug] /exe - Error: string index out of trange. exe -h creates Traceback

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#1494]
Attempting to try the EXE function and get errors:

```
2022 Mar 16, 02:51 (✨) / $ exe
Error: string index out of range

2022 Mar 16, 02:51 (✨) / $ exe -h
Traceback (most recent call last):
  File "terminal.py", line 775, in <module>
    main(
  File "terminal.py", line 716, in main
    terminal()
  File "terminal.py", line 472, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/Users/danglewood/GitHub/GamestonkTerminal/gamestonk_terminal/decorators.py", line 66, in wrapper
    console.print(f"[red]Error: {e}\n[/red]")
  File "/Users/danglewood/GitHub/GamestonkTerminal/gamestonk_terminal/rich_config.py", line 72, in print
    self.console.print(*args, **kwargs)
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/site-packages/rich/console.py", line 1595, in print
    renderables = self._collect_renderables(
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/site-packages/rich/console.py", line 1459, in _collect_renderables
    self.render_str(
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/site-packages/rich/console.py", line 1351, in render_str
    rich_text = render_markup(
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/site-packages/rich/markup.py", line 159, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/red]' at position 75 doesn't match any open tag
```

**Comment by DidierRLopes** [comment]
Nice find. Am on it
