### ISSUE TITLE
[Bug] stocks/ca/overview crashes

### ISSUE THREAD

**Issue by DidierRLopes** [GamestonkTerminal/GamestonkTerminal#1511]
`python terminal stocks/load aal/ca/getpoly/overview` crashes

**Comment by DidierRLopes** [comment]
This is the issue 

```
2022 Mar 18, 06:05 (✨) /stocks/ca/ $ overview
Traceback (most recent call last):
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/terminal.py", line 855, in <module>
    main(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/terminal.py", line 797, in main
    terminal()
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/terminal.py", line 538, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 185, in switch
    getattr(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/terminal.py", line 170, in call_stocks
    self.queue = self.load_class(StocksController, self.queue)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 120, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 308, in menu
    self.queue = self.switch(an_input)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 185, in switch
    getattr(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/stocks/stocks_controller.py", line 466, in call_ca
    self.queue = self.load_class(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 120, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 308, in menu
    self.queue = self.switch(an_input)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 185, in switch
    getattr(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/stocks/comparison_analysis/ca_controller.py", line 835, in call_overview
    finviz_compare_view.screener(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/stocks/comparison_analysis/finviz_compare_view.py", line 29, in screener
    df_screen = finviz_compare_model.get_comparison_data(data_type, similar)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/stocks/comparison_analysis/finviz_compare_model.py", line 89, in get_comparison_data
    return screen.screener_view(verbose=0)
AttributeError: 'Overview' object has no attribute 'screener_view'
```

**Comment by jmaslek** [comment]
Have you updated with poetry install recently?

**Comment by DidierRLopes** [comment]
Did now, and the error is different but still bug 😄 

```
 Installing pyex (0.5.0)
  • Installing pylint (2.12.2)
  • Installing pymongo (3.11.0)
  • Installing pyportfolioopt (1.5.1)
  • Installing pytest-cov (3.0.0)
  • Installing pytest-mock (3.7.0)
  • Installing pytest-recording (0.12.0)
  • Installing python-binance (1.0.15)
  • Installing python-coinmarketcap (0.2)
  • Installing pytrends (4.8.0): Installing...
  • Installing pyupgrade (2.31.1)
  • Installing quandl (3.7.0)
  • Installing rapidfuzz (1.9.1)
  • Installing reportlab (3.6.8)
  • Installing rich (10.16.2)
  • Installing robin-stocks (2.1.0)
  • Installing screeninfo (0.6.7): Installing...
  • Installing pyupgrade (2.31.1)
  • Installing quandl (3.7.0)
  • Installing rapidfuzz (1.9.1)
  • Installing reportlab (3.6.8)
  • Installing rich (10.16.2)
  • Installing robin-stocks (2.1.0)
  • Installing screeninfo (0.6.7): Installing...
  • Installing pytrends (4.8.0)
  • Installing pyupgrade (2.31.1)
  • Installing quandl (3.7.0)
  • Installing rapidfuzz (1.9.1)
  • Installing reportlab (3.6.8)
  • Installing rich (10.16.2)
  • Installing robin-stocks (2.1.0)
  • Installing screeninfo (0.6.7): Installing...
  • Installing screeninfo (0.6.7)
  • Installing seaborn (0.11.2)
  • Installing sentiment-investor (2.1.0)
  • Installing squarify (0.4.3)
  • Installing thepassiveinvestor (1.0.10)
  • Installing tradingview-ta (3.2.10)
  • Installing types-python-dateutil (2.8.9)
  • Installing types-pytz (2021.3.5)
  • Installing types-pyyaml (6.0.4)
  • Installing types-requests (2.27.12)
  • Installing types-setuptools (57.4.10)
  • Installing vadersentiment (3.3.2)
  • Installing valinvest (0.0.2)
  • Installing voila (0.3.3)
  • Installing yfinance (0.1.70)

Installing the current project: GamestonkTerminal (0.1.0)
~/Documents/git/GamestonkTerminal (main) $ python3 terminal.py 

Welcome to Gamestonk Terminal Beta

╭───────────────────────────────────────────────────────────────────────────────────────── Home ─────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                        │
│ Multiple jobs queue (where each '/' denotes a new command).                                                                                                                            │
│     E.g. '/stocks $ disc/ugs -n 3/../load tsla/candle'                                                                                                                                 │
│                                                                                                                                                                                        │
│ If you want to jump from crypto/ta to stocks you can use an absolute path that starts with a slash (/).                                                                                │
│     E.g. '/crypto/ta $ /stocks'                                                                                                                                                        │
│                                                                                                                                                                                        │
│ The previous logic also holds for when launching the terminal.                                                                                                                         │
│     E.g. '$ python terminal.py /stocks/disc/ugs -n 3/../load tsla/candle'                                                                                                              │
│                                                                                                                                                                                        │
│ You can run a standalone .gst routine file with:                                                                                                                                       │
│     E.g. '$ python terminal.py routines/example.gst'                                                                                                                                   │
│                                                                                                                                                                                        │
│ You can run a .gst routine file with variable inputs:                                                                                                                                  │
│     E.g. '$ python terminal.py routines/example_with_inputs.gst --input pltr,tsla,nio'                                                                                                 │
│                                                                                                                                                                                        │
│ The main commands you should be aware when navigating through the terminal are:                                                                                                        │
│     cls             clear the screen                                                                                                                                                   │
│     help / h / ?    help menu                                                                                                                                                          │
│     quit / q / ..   quit this menu and go one menu above                                                                                                                               │
│     exit            exit the terminal                                                                                                                                                  │
│     reset / r       reset the terminal and reload configs from the current location                                                                                                    │
│     resources       only available on main contexts (not sub-menus)                                                                                                                    │
│                                                                                                                                                                                        │
│     about           about us                                                                                                                                                           │
│     update          update terminal automatically                                                                                                                                      │
│     tz              set different timezone                                                                                                                                             │
│     export          select export folder to output data                                                                                                                                │
│     exe             execute automated routine script                                                                                                                                   │
│ >   settings        set feature flags and style charts                                                                                                                                 │
│ >   keys            set API keys and check their validity                                                                                                                              │
│                                                                                                                                                                                        │
│ Export Folder: DEFAULT (folder: exports/)                                                                                                                                              │
│ Timezone:      America/New_York                                                                                                                                                        │
│                                                                                                                                                                                        │
│ >   stocks                                                                                                                                                                             │
│ >   crypto                                                                                                                                                                             │
│ >   etf                                                                                                                                                                                │
│ >   economy                                                                                                                                                                            │
│ >   forex                                                                                                                                                                              │
│ >   funds                                                                                                                                                                              │
│ >   alternative                                                                                                                                                                        │
│ >   econometrics                                                                                                                                                                       │
│ >   portfolio                                                                                                                                                                          │
│ >   jupyter                                                                                                                                                                            │
│                                                                                                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Gamestonk Terminal ─╯
2022 Mar 18, 17:50 (✨) / $ stocks/load aal/ca/getpoly/overview
2022 Mar 18, 17:50 (✨) /stocks/ $ load aal

Loading Daily AAL stock with starting period 2019-03-13 for analysis.

Datetime: 2022 Mar 18 17:50
Timezone: America/New_York
Currency: USD
Market:   CLOSED

2022 Mar 18, 17:50 (✨) /stocks/ $ ca
2022 Mar 18, 17:50 (✨) /stocks/ca/ $ getpoly
[Polygon] Similar Companies: AAL, SKYW, JBLU, HA, ALGT, ALK, LUV, DAL, LTM, SAVE, UAL 

2022 Mar 18, 17:50 (✨) /stocks/ca/ $ overview
Error: 'Overview' object has no attribute 'screener_view'

Error: 'list' object has no attribute 'empty'

2022 Mar 18, 17:50 (✨) /stocks/ca/ $
```

**Comment by jmaslek** [comment]
what's going on with your env? lo
<img width="930" alt="Screen Shot 2022-03-18 at 6 24 07 PM" src="https://user-images.githubusercontent.com/18151143/159092387-ed4a863d-889e-49ca-8d6b-c461d09c9411.png">
l

**Comment by minhhoang1023** [comment]
It worked on my side too. @DidierRLopes Could you confirm if your finvizfinance is 0.12.2 version? This error is due to the finvinzfinance upgrade I did a few weeks ago.

**Comment by DidierRLopes** [comment]
Sorry, missed this. 

It should be good! Will close this, thanks!
