### ISSUE TITLE
[Bug] Logging: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 145: invalid start byte

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#1522]
This error breaks the Terminal while launching. 

```
(gst) MacPro-31:GamestonkTerminal DeeLee$ python terminal.py
Traceback (most recent call last):
  File "terminal.py", line 820, in <module>
    main(
  File "terminal.py", line 762, in main
    terminal()
  File "terminal.py", line 422, in terminal
    setup_logging(appName)
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/loggers.py", line 244, in setup_logging
    setup_file_logger(app_name, str(START_TIME))
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/loggers.py", line 85, in setup_file_logger
    upload_archive_logs_s3(directory_str=uuid_log_dir, log_filter=r"gst_")
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/loggers.py", line 373, in upload_archive_logs_s3
    if not unused_file and contains_goodbye(file):
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/loggers.py", line 329, in contains_goodbye
    last_line = f.readline().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 145: invalid start byte
```

**Comment by deeleeramone** [comment]
on another machine (Mac M1/OS 12.3) the error is different, and does not prevent the terminal from launching. 

```
(gst) Danglewoods-MacBook-Pro:GamestonkTerminal danglewood$ python terminal.py
Could not find last line
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/GamestonkTerminal/gamestonk_terminal/loggers.py", line 324, in contains_goodbye
    f.seek(-2, os.SEEK_CUR)
OSError: [Errno 22] Invalid argument
```
