### ISSUE TITLE
[Bug] Logging - error message 

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#1542]
```
(gst) MacPro-31:GamestonkTerminal DeeLee$ python terminal.py
--- Logging error ---
Traceback (most recent call last):
  File "/Users/DeeLee/Applications/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/Users/DeeLee/Applications/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
ValueError: write to closed file
Call stack:
  File "terminal.py", line 805, in <module>
    main(
  File "terminal.py", line 747, in main
    terminal()
  File "terminal.py", line 422, in terminal
    setup_logging(appName)
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/loggers.py", line 162, in setup_logging
    setup_handlers(settings=settings)
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/loggers.py", line 120, in setup_handlers
    logger.info("Logging set to %s", handler_list)
Message: 'Logging set to %s'
Arguments: ('file',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/DeeLee/Applications/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/Users/DeeLee/Applications/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
ValueError: write to closed file
Call stack:
  File "terminal.py", line 805, in <module>
    main(
  File "terminal.py", line 747, in main
    terminal()
  File "terminal.py", line 422, in terminal
    setup_logging(appName)
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/loggers.py", line 162, in setup_logging
    setup_handlers(settings=settings)
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/loggers.py", line 122, in setup_handlers
    logger.info(
Message: 'LOGFORMAT: %s%s'
Arguments: ('%(levelname)s-%(appName)s-%(commitHash)s-%(appId)s-%(sessionId)s-%(userId)s-', '%(asctime)s-%(name)s-%(funcName)s-%(lineno)s-%(message)s')
--- Logging error ---
Traceback (most recent call last):
  File "/Users/DeeLee/Applications/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/Users/DeeLee/Applications/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
ValueError: write to closed file
Call stack:
  File "terminal.py", line 805, in <module>
    main(
  File "terminal.py", line 747, in main
    terminal()
  File "terminal.py", line 424, in terminal
    log_settings()
  File "terminal.py", line 590, in log_settings
    logger.info("SETTINGS: %s ", str(settings_dict))
Message: 'SETTINGS: %s '
Arguments: ("{'tab': 'True', 'cls': 'False', 'color': 'True', 'promptkit': 'True', 'predict': 'True', 'thoughts': 'False', 'reporthtml': 'True', 'exithelp': 'False', 'rcontext': 'True', 'rich': 'True', 'richpanel': 'True', 'ion': 'True', 'watermark': 'False', 'autoscaling': 'True', 'dt': 'True', 'python': '3.8.12', 'os': 'Darwin'}",)

$ Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/DeeLee/Applications/miniconda3/envs/gst/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/log/collection/logging_clock.py", line 106, in run
    self.do_action_every_sharp(
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/log/collection/logging_clock.py", line 92, in do_action_every_sharp
    action()
  File "/Users/DeeLee/GamestonkTerminal/gamestonk_terminal/log/generation/path_tracking_file_handler.py", line 92, in doRollover
    super().doRollover()
  File "/Users/DeeLee/Applications/miniconda3/envs/gst/lib/python3.8/logging/handlers.py", line 393, in doRollover
    os.remove(dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/DeeLee/GamestonkTerminal/logs/5794a13c-b057-4b80-97ed-7a46cd8e0601/gst_1648077468.2022-03-23_16.log'
```

![image](https://user-images.githubusercontent.com/85772166/159814411-4accd0f7-4b89-4b06-8f7c-64d300c6b2cc.png)

**Comment by deeleeramone** [comment]
![Screen Shot 2022-03-23 at 4 49 00 PM](https://user-images.githubusercontent.com/85772166/159814818-8e5e7229-0ec3-48eb-80ce-46cd4a77c650.png)

**Comment by Chavithra** [comment]
Notes :
- Happening at the start of the Terminal.
- Issue doesn't happend when we disable LoggingClock thread : the log rotation + sending works

**Comment by deeleeramone** [comment]
Just updated 2021 Mac M1 machine, and got new messages. Terminal launches, but error message is different.
```
(gst) Danglewoods-MacBook-Pro:GamestonkTerminal danglewood$ python terminal.py
--- Logging error ---
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "terminal.py", line 805, in <module>
    main(
  File "terminal.py", line 747, in main
    terminal()
  File "terminal.py", line 422, in terminal
    setup_logging(appName)
  File "/Users/danglewood/GitHub/GamestonkTerminal/gamestonk_terminal/loggers.py", line 162, in setup_logging
    setup_handlers(settings=settings)
  File "/Users/danglewood/GitHub/GamestonkTerminal/gamestonk_terminal/loggers.py", line 119, in setup_handlers
    logger.info("Logging configuration finished")
Message: 'Logging configuration finished'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
ValueError: write to closed file
Call stack:
  File "terminal.py", line 805, in <module>
    main(
  File "terminal.py", line 747, in main
    terminal()
  File "terminal.py", line 423, in terminal
    logger.info("START")
Message: 'START'
Arguments: ()

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022 Mar 24, 02:02 (✨) / $     self.run()
  File "/Users/danglewood/GitHub/GamestonkTerminal/gamestonk_terminal/log/collection/logging_clock.py", line 106, in run
    self.do_action_every_sharp(
  File "/Users/danglewood/GitHub/GamestonkTerminal/gamestonk_terminal/log/collection/logging_clock.py", line 92, in do_action_every_sharp
    action()
  File "/Users/danglewood/GitHub/GamestonkTerminal/gamestonk_terminal/log/generation/path_tracking_file_handler.py", line 92, in doRollover
    super().doRollover()
  File "/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/logging/handlers.py", line 393, in doRollover
    os.remove(dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/danglewood/GitHub/GamestonkTerminal/logs/90d1e74b-95b2-4f61-8f74-02bed5b46ff8/gst_1648101726.2022-03-23_23.log'
```
