### ISSUE TITLE
[Bug] Container error git.exc.InvalidGitRepositoryError

### ISSUE THREAD

**Issue by duviful** [GamestonkTerminal/GamestonkTerminal#516]
**Describe the bug**
I'm unable to run the docker container.
The build is successful but the container dies instantly with the following error
```
Traceback (most recent call last):
  File "terminal.py", line 559, in <module>
    terminal()
  File "terminal.py", line 493, in terminal
    bootup()
  File "/home/python/gamestonk_terminal/main_helper.py", line 757, in bootup
    f"\nWelcome to Gamestonk Terminal Beta ({str(git.Repo('.').head.commit)[:7]})"
  File "/home/python/.local/lib/python3.6/site-packages/git/repo/base.py", line 220, in __init__
    self.working_dir = self._working_tree_dir or self.common_dir  # type: Optional[PathLike]
  File "/home/python/.local/lib/python3.6/site-packages/git/repo/base.py", line 303, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

using docker-compose up has a very similar results with at the addition of this two lines 
```
gamestonkterminal_1  | Warning: Output is not a terminal (fd=1).
gamestonkterminal_1  | Warning: Input is not a terminal (fd=0).
```

**To Reproduce**
`docker build .`
`docker run -it gamestonkterminal:dev `

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Docker version 20.10.6, build 370c289

Best
Thanks

**Comment by DidierRLopes** [comment]
can you try to "pip install gitpython" ?

**Comment by duviful** [comment]
I did install that on my local machine:
`Installing collected packages: smmap, gitdb, gitpython`

after I run again the following:
`docker build .`
`docker run -it gamestonkterminal:dev`

result is still the same

```bash
docker run -it gamestonkterminal:dev
Traceback (most recent call last):
  File "terminal.py", line 559, in <module>
    terminal()
  File "terminal.py", line 493, in terminal
    bootup()
  File "/home/python/gamestonk_terminal/main_helper.py", line 757, in bootup
    f"\nWelcome to Gamestonk Terminal Beta ({str(git.Repo('.').head.commit)[:7]})"
  File "/home/python/.local/lib/python3.6/site-packages/git/repo/base.py", line 220, in __init__
    self.working_dir = self._working_tree_dir or self.common_dir  # type: Optional[PathLike]
  File "/home/python/.local/lib/python3.6/site-packages/git/repo/base.py", line 303, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError```

**Comment by DidierRLopes** [comment]
Can you try now? I'm closing this ticket as #526 should fix this. If it doesn't just re-open this ticket please! Thanks!

**Comment by duviful** [comment]
works now. thanks.
