### ISSUE TITLE
[Bug] Sentiment Investment's popular ticker command gives error, Keyerror: 'popularsi'

### ISSUE THREAD

**Issue by sug4ndh** [GamestonkTerminal/GamestonkTerminal#755]
**Describe the bug**
When executing popularsi within ba menu, keyerror: 'popularsi' is raised.

**To Reproduce**
1. Go inside stocks menu
2. Load a ticker, RWLK, for e.g.
3. Go inside ba menu
4. Execute popularsi command 

**Trace log**
```
Traceback (most recent call last):
  File "terminal.py", line 312, in <module>
    terminal()
  File "terminal.py", line 285, in terminal
    process_input = t_controller.switch(an_input)
  File "terminal.py", line 124, in switch
    return getattr(
  File "terminal.py", line 167, in call_s
    return self.call_stocks(_)
  File "terminal.py", line 163, in call_stocks
    return stocks_controller.menu()
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/stocks_controller.py", line 523, in menu
    process_input = stocks_controller.switch(an_input)
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/stocks_controller.py", line 175, in switch
    return getattr(
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/stocks_controller.py", line 427, in call_ba
    ret = ba_controller.menu(
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py", line 305, in menu
    process_input = ba_controller.switch(an_input)
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py", line 144, in switch
    return getattr(
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py", line 278, in call_popularsi
    sentimentinvestor_view.sort_sentiment("AHI", other_args, "popularsi")
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/common/behavioural_analysis/sentimentinvestor_view.py", line 78, in sort_sentiment
    description=textwrap.dedent(__command_descriptions[command_name]),
KeyError: 'popularsi'

```

**Desktop (please complete the following information):**
 - OS: Linux mint 20
 - Python version [e.g. 3.8.0]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by DidierRLopes** [comment]
Just created a fix for this
